# Configurações de build para a Netlify
[build]
  command = "npm run build"
  publish = "dist"
  base = "frontend"

# Redirecionamento para Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
